Vagrant.configure(2) do |config|
  config.vm.define "Lesson15-backup-client" do |subconfig|
  subconfig.vm.box = "centos/8"
  subconfig.vm.hostname="Lesson15-backup-client"
  subconfig.vm.network :private_network, ip: "192.168.50.11"
  subconfig.vm.provider "virtualbox" do |vb|
  vb.memory = "1024"
  vb.cpus = "1"
  end
  end
  config.vm.define "Lesson15-backup-server" do |subconfig|
  subconfig.vm.box = "centos/8"
  subconfig.vm.hostname="Lesson15-backup-server"
  subconfig.vm.network :private_network, ip: "192.168.50.12"
  subconfig.vm.provider "virtualbox" do |vb|
  vb.memory = "1024"
  vb.cpus = "1"
  second_disk = "disk2.vdi"
  unless File.exist?(second_disk)
    vb.customize ['createhd', '--filename', second_disk, '--size', 2 * 1024]
    vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', second_disk]
  subconfig.vm.provision :shell, :path => "provision/1-mkdir.sh"
  end
  end
  config.ssh.insert_key = false
  config.ssh.private_key_path = ['~/.vagrant.d/insecure_private_key', '~/.ssh/id_rsa']
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
  config.vm.provision :shell, :path => "provision/0-whoami.sh"
  end
  end
