---
- name: Ensure override directory exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: Create override file
  template:
    src: override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
  notify:
    - Restart docker

- name: Reload systemd
  systemd:
    daemon-reload: yes

- name: Enable and start docker.service
  systemd:
    name: docker.service
    state: started
    enabled: yes
