---
- name: create node_exporter system group
  group:
    name: "{{ node_exporter_group }}"
    system: true
    state: present
  when: node_exporter_group != "root"

- name: create node_exporter system user
  user:
    name: "{{ node_exporter_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ node_exporter_group }}"
    append: yes
    createhome: false
    home: "/"
  when: node_exporter_user != "root"
