---
- name: create prometheus system group
  group:
    name: "{{ prometheus_group }}"
    system: true
    state: present

- name: create prometheus system user
  user:
    name: "{{ prometheus_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ prometheus_group }}"
    createhome: false
    home: "{{ prometheus_db_dir }}"
